/**
 * @file    main.c
 * @brief   Application entry point — hardware init, RTOS object creation,
 *          and scheduler start.
 *
 * Peripheral initialisation (clock, GPIO, I²C, UART, SPI, SDMMC, TIM, IWDG)
 * is handled by STM32CubeMX-generated MX_* functions exactly as before.
 * The bare-metal super-loop is replaced entirely by:
 *
 *   1. Mutex creation (sensor_data_mutex, gps_data_mutex)
 *   2. Task creation (accel, temp, gps, logger, scan, watchdog)
 *   3. vTaskStartScheduler()
 *
 * Task priority summary (higher = more urgent):
 *
 *   TASK_PRIO_ACCEL    6   Sensor-B read at 100 Hz
 *   TASK_PRIO_GPS      5   GPS poll at 5 Hz
 *   TASK_PRIO_TEMP     4   Sensor-A + Sensor-C read at 10 Hz
 *   TASK_PRIO_LOGGER   3   SD write at 10 Hz, RS232 at 2 Hz
 *   TASK_PRIO_WATCHDOG 2   IWDG feed every 500 ms
 *   TASK_PRIO_SCAN     1   Hot-plug I²C scan every 2 s
 *   tskIDLE_PRIORITY   0   FreeRTOS idle task
 */

#include "main.h"
#include "fatfs.h"
#include "usb_device.h"

/* Application headers */
#include "app_config.h"
#include "shared_data.h"
#include "sd_writer.h"

/* Task headers */
#include "tasks/task_accel.h"
#include "tasks/task_temp.h"
#include "tasks/task_gps.h"
#include "tasks/task_logger.h"
#include "tasks/task_scan.h"
#include "tasks/task_watchdog.h"

/* FreeRTOS */
#include "FreeRTOS.h"
#include "task.h"
#include "semphr.h"

/* ── Hardware handles (generated by CubeMX) ───────────────────────────────── */
I2C_HandleTypeDef  hi2c1, hi2c2, hi2c3, hi2c4;
UART_HandleTypeDef huart1, huart6;
SPI_HandleTypeDef  hspi1;
TIM_HandleTypeDef  htim2;
IWDG_HandleTypeDef hiwdg1;

/* ── Application globals ──────────────────────────────────────────────────── */
uint16_t g_flight_number = 0;

/* ── Private function prototypes ──────────────────────────────────────────── */
static void SystemClock_Config(void);
static void MPU_Config(void);
static void MX_GPIO_Init(void);
static void MX_I2C1_Init(void);
static void MX_I2C2_Init(void);
static void MX_I2C3_Init(void);
static void MX_I2C4_Init(void);
static void MX_TIM2_Init(void);
static void MX_USART1_UART_Init(void);
static void MX_USART6_UART_Init(void);
static void MX_SPI1_Init(void);
static void MX_IWDG1_Init(void);

/* ── Entry point ──────────────────────────────────────────────────────────── */

int main(void)
{
    /* ── Core init ─────────────────────────────────────────────────────────── */
    MPU_Config();
    HAL_Init();
    SystemClock_Config();

    /* ── Peripheral init ───────────────────────────────────────────────────── */
    MX_GPIO_Init();
    MX_I2C1_Init();
    MX_I2C2_Init();
    MX_I2C3_Init();
    MX_I2C4_Init();
    MX_SDMMC1_SD_Init();
    MX_FATFS_Init();
    MX_USB_DEVICE_Init();
    MX_TIM2_Init();
    MX_USART1_UART_Init();
    MX_USART6_UART_Init();
    MX_SPI1_Init();
    MX_IWDG1_Init();

    /* ── Application init ──────────────────────────────────────────────────── */
    HAL_Delay(50);          /* Allow SD and USB to settle after power-on      */
    sd_writer_init();
    g_flight_number = sd_writer_get_flight_number();

    /* ── Zero shared data ──────────────────────────────────────────────────── */
    memset(&globalSensorData, 0, sizeof(globalSensorData));
    memset(&globalGPSData,    0, sizeof(globalGPSData));

    /* ── Create RTOS synchronisation objects ───────────────────────────────── */
    sensor_data_mutex = xSemaphoreCreateMutex();
    gps_data_mutex    = xSemaphoreCreateMutex();

    configASSERT(sensor_data_mutex != NULL);
    configASSERT(gps_data_mutex    != NULL);

    /* ── Create tasks ──────────────────────────────────────────────────────── */
    xTaskCreate(task_accel,    "accel",    STACK_ACCEL,    NULL, TASK_PRIO_ACCEL,    NULL);
    xTaskCreate(task_temp,     "temp",     STACK_TEMP,     NULL, TASK_PRIO_TEMP,     NULL);
    xTaskCreate(task_gps,      "gps",      STACK_GPS,      NULL, TASK_PRIO_GPS,      NULL);
    xTaskCreate(task_logger,   "logger",   STACK_LOGGER,   NULL, TASK_PRIO_LOGGER,   NULL);
    xTaskCreate(task_watchdog, "wdog",     STACK_WATCHDOG, NULL, TASK_PRIO_WATCHDOG, NULL);
    xTaskCreate(task_scan,     "scan",     STACK_SCAN,     NULL, TASK_PRIO_SCAN,     NULL);

    /* ── Start scheduler (does not return) ─────────────────────────────────── */
    vTaskStartScheduler();

    /* Should never reach here — trap if scheduler fails to start */
    for (;;) {}
}

/* ── FreeRTOS stack overflow hook ──────────────────────────────────────────── */
void vApplicationStackOverflowHook(TaskHandle_t xTask, char *pcTaskName)
{
    (void)xTask;
    (void)pcTaskName;
    /* In production: log to SD if possible, then reset */
    NVIC_SystemReset();
}

/* ── FreeRTOS malloc failed hook ───────────────────────────────────────────── */
void vApplicationMallocFailedHook(void)
{
    NVIC_SystemReset();
}

/* ── HAL error handler ─────────────────────────────────────────────────────── */
void Error_Handler(void)
{
    __disable_irq();
    while (1) {}
}

/*
 * Note: SystemClock_Config(), MPU_Config(), and all MX_* peripheral init
 * functions are identical to the CubeMX-generated versions in the original
 * bare-metal project.  They are intentionally omitted here to keep this
 * file focused on the RTOS architecture.  Copy them from the CubeMX output
 * or regenerate using the provided .ioc file.
 */
